/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\zhuboyong\\vuepressDemo1\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-638d3cb6",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-638d3cb6").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-f916a62e",
    path: "/about/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f916a62e").then(next)
    },
  },
  {
    name: "v-2d378a54",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d378a54").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-0a66b246",
    path: "/about/contact/qq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a66b246").then(next)
    },
  },
  {
    name: "v-7f058f3a",
    path: "/about/contact/wechat.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f058f3a").then(next)
    },
  },
  {
    name: "v-2a008288",
    path: "/blog/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a008288").then(next)
    },
  },
  {
    path: "/blog/index.html",
    redirect: "/blog/"
  },
  {
    name: "v-40a34e43",
    path: "/blog/first-post.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40a34e43").then(next)
    },
  },
  {
    name: "v-d558076a",
    path: "/blog/test1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d558076a").then(next)
    },
  },
  {
    name: "v-707ee5b8",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-707ee5b8").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-6ef23fd4",
    path: "/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ef23fd4").then(next)
    },
  },
  {
    name: "v-2ae6eee9",
    path: "/guide/using-kinsta-stsh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ae6eee9").then(next)
    },
  },
  {
    name: "v-520c4332",
    path: "/tools/Everything.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-520c4332").then(next)
    },
  },
  {
    name: "v-3ee82742",
    path: "/tools/IDEA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ee82742").then(next)
    },
  },
  {
    name: "v-51fea9c9",
    path: "/tools/Jetbrains.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51fea9c9").then(next)
    },
  },
  {
    name: "v-aaad448c",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aaad448c").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-9cc8780e",
    path: "/tools/VScode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9cc8780e").then(next)
    },
  },
  {
    name: "v-77f45c45",
    path: "/tools/Vite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77f45c45").then(next)
    },
  },
  {
    name: "v-e040e472",
    path: "/tools/Wappalyzer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e040e472").then(next)
    },
  },
  {
    name: "v-790fa7ae",
    path: "/tools/Windows.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-790fa7ae").then(next)
    },
  },
  {
    name: "v-06fb3fa9",
    path: "/tools/WindowsTerminal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06fb3fa9").then(next)
    },
  },
  {
    name: "v-2f5369ce",
    path: "/tools/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f5369ce").then(next)
    },
  },
  {
    name: "v-4f7d2756",
    path: "/troubleshooting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f7d2756").then(next)
    },
  },
  {
    name: "v-14b97908",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14b97908").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-439dc98a",
    path: "/zh/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-439dc98a").then(next)
    },
  },
  {
    path: "/zh/about/index.html",
    redirect: "/zh/about/"
  },
  {
    name: "v-fed92c70",
    path: "/zh/about/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fed92c70").then(next)
    },
  },
  {
    name: "v-6f9fd7dd",
    path: "/zh/about/contact/qq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f9fd7dd").then(next)
    },
  },
  {
    name: "v-19645b9d",
    path: "/zh/about/contact/wechat.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19645b9d").then(next)
    },
  },
  {
    name: "v-8b84b3c6",
    path: "/zh/blog/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b84b3c6").then(next)
    },
  },
  {
    path: "/zh/blog/index.html",
    redirect: "/zh/blog/"
  },
  {
    name: "v-d992ded4",
    path: "/zh/blog/test1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d992ded4").then(next)
    },
  },
  {
    name: "v-02881e60",
    path: "/zh/blog/first-post.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02881e60").then(next)
    },
  },
  {
    name: "v-4db4fb9b",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4db4fb9b").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-491ccd20",
    path: "/zh/guide/using-kinsta-stsh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-491ccd20").then(next)
    },
  },
  {
    name: "v-65f4cd30",
    path: "/zh/tools/Everything.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65f4cd30").then(next)
    },
  },
  {
    name: "v-4ae869b0",
    path: "/zh/tools/IDEA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ae869b0").then(next)
    },
  },
  {
    name: "v-ece49d4c",
    path: "/zh/tools/Jetbrains.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ece49d4c").then(next)
    },
  },
  {
    name: "v-589c9c0a",
    path: "/zh/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-589c9c0a").then(next)
    },
  },
  {
    path: "/zh/tools/index.html",
    redirect: "/zh/tools/"
  },
  {
    name: "v-f21846e0",
    path: "/zh/tools/VScode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f21846e0").then(next)
    },
  },
  {
    name: "v-a02ffbe0",
    path: "/zh/tools/Vite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a02ffbe0").then(next)
    },
  },
  {
    name: "v-a184b1a0",
    path: "/zh/tools/Wappalyzer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a184b1a0").then(next)
    },
  },
  {
    name: "v-3093d100",
    path: "/zh/tools/Windows.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3093d100").then(next)
    },
  },
  {
    name: "v-62c3e948",
    path: "/zh/tools/WindowsTerminal.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62c3e948").then(next)
    },
  },
  {
    name: "v-514bcf60",
    path: "/zh/tools/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-514bcf60").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]