/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "XXX System",
  "description": "A VuePress QuickStart for Kinsta",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": "A VuePress QuickStart",
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Simplicity first",
            "details": "A Markdown centric project structure that helps you focus on writing with minimal configuration."
          },
          {
            "title": "Vue drive",
            "details": "Enjoy the development experience of Vue+webpack, use Vue components in Markdown, and also use Vue to develop custom themes."
          },
          {
            "title": "High performance",
            "details": "VuePress pre renders static HTML for each page and runs it as SPA when the page is loaded."
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-638d3cb6",
      "path": "/"
    },
    {
      "title": "About this site",
      "frontmatter": {
        "id": "about",
        "slug": "/about",
        "title": "About this site"
      },
      "regularPath": "/about/about.html",
      "relativePath": "about/about.md",
      "key": "v-f916a62e",
      "path": "/about/about.html",
      "headers": [
        {
          "level": 2,
          "title": "Location of this site",
          "slug": "location-of-this-site"
        },
        {
          "level": 2,
          "title": "Deployment plan",
          "slug": "deployment-plan"
        },
        {
          "level": 2,
          "title": "Thank you for watching",
          "slug": "thank-you-for-watching"
        }
      ]
    },
    {
      "title": "About",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-2d378a54",
      "path": "/about/"
    },
    {
      "title": "qq",
      "frontmatter": {
        "title": "qq"
      },
      "regularPath": "/about/contact/qq.html",
      "relativePath": "about/contact/qq.md",
      "key": "v-0a66b246",
      "path": "/about/contact/qq.html"
    },
    {
      "title": "wechat",
      "frontmatter": {
        "title": "wechat"
      },
      "regularPath": "/about/contact/wechat.html",
      "relativePath": "about/contact/wechat.md",
      "key": "v-7f058f3a",
      "path": "/about/contact/wechat.html"
    },
    {
      "title": "Blog",
      "frontmatter": {
        "blog_index": true
      },
      "regularPath": "/blog/",
      "relativePath": "blog/README.md",
      "key": "v-2a008288",
      "path": "/blog/"
    },
    {
      "title": "My Exciting VuePress Blog Journey",
      "frontmatter": {
        "title": "My Exciting VuePress Blog Journey",
        "date": "2023-09-28T00:00:00.000Z",
        "description": "Exploring VuePress, a versatile static site generator, and sharing my experiences along the way."
      },
      "regularPath": "/blog/first-post.html",
      "relativePath": "blog/first-post.md",
      "key": "v-40a34e43",
      "path": "/blog/first-post.html"
    },
    {
      "title": "title1",
      "frontmatter": {
        "title": "title1",
        "date": "2023-09-28T00:00:00.000Z",
        "description": "this is a description."
      },
      "regularPath": "/blog/test1.html",
      "relativePath": "blog/test1.md",
      "key": "v-d558076a",
      "path": "/blog/test1.html"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-707ee5b8",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Static Site Hosting",
          "slug": "static-site-hosting"
        }
      ]
    },
    {
      "title": "Getting Started with VuePress",
      "frontmatter": {},
      "regularPath": "/getting-started.html",
      "relativePath": "getting-started.md",
      "key": "v-6ef23fd4",
      "path": "/getting-started.html",
      "headers": [
        {
          "level": 2,
          "title": "Installation",
          "slug": "installation"
        }
      ]
    },
    {
      "title": "How Kinsta Static Site Hosting Works",
      "frontmatter": {},
      "regularPath": "/guide/using-kinsta-stsh.html",
      "relativePath": "guide/using-kinsta-stsh.md",
      "key": "v-2ae6eee9",
      "path": "/guide/using-kinsta-stsh.html"
    },
    {
      "title": "Everything快速搜索本地文件",
      "frontmatter": {
        "title": "Everything快速搜索本地文件",
        "date": "2020-09-08T00:00:00.000Z",
        "tags": [
          "工具"
        ],
        "keywords": [
          "工具"
        ]
      },
      "regularPath": "/tools/Everything.html",
      "relativePath": "tools/Everything.md",
      "key": "v-520c4332",
      "path": "/tools/Everything.html",
      "headers": [
        {
          "level": 2,
          "title": "软件说明",
          "slug": "软件说明"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "设置打开快捷键",
          "slug": "设置打开快捷键"
        },
        {
          "level": 2,
          "title": "搜索文件",
          "slug": "搜索文件"
        },
        {
          "level": 3,
          "title": "右键搜索 Everything",
          "slug": "右键搜索-everything"
        },
        {
          "level": 2,
          "title": "一些注意的坑",
          "slug": "一些注意的坑"
        },
        {
          "level": 3,
          "title": "全字匹配",
          "slug": "全字匹配"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "IDEA基本配置",
      "frontmatter": {
        "title": "IDEA基本配置",
        "date": "2022-01-06T00:00:00.000Z",
        "tags": [
          "Jetbrains",
          "idea",
          "java",
          "工具"
        ],
        "keywords": [
          "Jetbrains",
          "idea",
          "java",
          "工具"
        ]
      },
      "regularPath": "/tools/IDEA.html",
      "relativePath": "tools/IDEA.md",
      "key": "v-3ee82742",
      "path": "/tools/IDEA.html",
      "headers": [
        {
          "level": 2,
          "title": "插件",
          "slug": "插件"
        },
        {
          "level": 3,
          "title": "主题图标",
          "slug": "主题图标"
        },
        {
          "level": 2,
          "title": "快捷键",
          "slug": "快捷键"
        },
        {
          "level": 3,
          "title": "Ctrl",
          "slug": "ctrl"
        },
        {
          "level": 3,
          "title": "Alt",
          "slug": "alt"
        },
        {
          "level": 3,
          "title": "Ctrl + Alt",
          "slug": "ctrl-alt"
        },
        {
          "level": 3,
          "title": "Ctrl + Shift",
          "slug": "ctrl-shift"
        },
        {
          "level": 3,
          "title": "Alt + Shift",
          "slug": "alt-shift"
        },
        {
          "level": 3,
          "title": "调试",
          "slug": "调试"
        },
        {
          "level": 3,
          "title": "自定义",
          "slug": "自定义"
        },
        {
          "level": 2,
          "title": "其他操作",
          "slug": "其他操作"
        },
        {
          "level": 3,
          "title": "快速生成代码",
          "slug": "快速生成代码"
        },
        {
          "level": 3,
          "title": "修改 Maven 依赖仓库位置",
          "slug": "修改-maven-依赖仓库位置"
        },
        {
          "level": 2,
          "title": "配置导入与导出",
          "slug": "配置导入与导出"
        }
      ]
    },
    {
      "title": "Jetbrains系列产品激活方法",
      "frontmatter": {
        "title": "Jetbrains系列产品激活方法",
        "date": "2020-09-03T00:00:00.000Z",
        "tags": [
          "Jetbrains",
          "工具"
        ],
        "keywords": [
          "Jetbrains",
          "工具"
        ]
      },
      "regularPath": "/tools/Jetbrains.html",
      "relativePath": "tools/Jetbrains.md",
      "key": "v-51fea9c9",
      "path": "/tools/Jetbrains.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "开始激活",
          "slug": "开始激活"
        },
        {
          "level": 3,
          "title": "下载激活工具",
          "slug": "下载激活工具"
        },
        {
          "level": 3,
          "title": "运行要激活的软件",
          "slug": "运行要激活的软件"
        },
        {
          "level": 3,
          "title": "补充几点",
          "slug": "补充几点"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Tools",
      "frontmatter": {},
      "regularPath": "/tools/",
      "relativePath": "tools/README.md",
      "key": "v-aaad448c",
      "path": "/tools/"
    },
    {
      "title": "VScode相关配置",
      "frontmatter": {
        "title": "VScode相关配置",
        "date": "2021-08-03T00:00:00.000Z",
        "tags": [
          "vscode",
          "开发工具",
          "配置"
        ],
        "keywords": [
          "vscode",
          "开发工具",
          "配置"
        ]
      },
      "regularPath": "/tools/VScode.html",
      "relativePath": "tools/VScode.md",
      "key": "v-9cc8780e",
      "path": "/tools/VScode.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "插件推荐",
          "slug": "插件推荐"
        },
        {
          "level": 3,
          "title": "GitHub Copilot",
          "slug": "github-copilot"
        },
        {
          "level": 3,
          "title": "Bracket Pair Colorizer 2",
          "slug": "bracket-pair-colorizer-2"
        },
        {
          "level": 3,
          "title": "indent-rainbow",
          "slug": "indent-rainbow"
        },
        {
          "level": 3,
          "title": "Prettier",
          "slug": "prettier"
        },
        {
          "level": 3,
          "title": "ESLint",
          "slug": "eslint"
        },
        {
          "level": 3,
          "title": "Turbo Console Log",
          "slug": "turbo-console-log"
        },
        {
          "level": 3,
          "title": "Live Server",
          "slug": "live-server"
        },
        {
          "level": 3,
          "title": "Live Share",
          "slug": "live-share"
        },
        {
          "level": 3,
          "title": "REST Client",
          "slug": "rest-client"
        },
        {
          "level": 3,
          "title": "Thunder Client",
          "slug": "thunder-client"
        },
        {
          "level": 3,
          "title": "CSS Peek",
          "slug": "css-peek"
        },
        {
          "level": 3,
          "title": "Project Manager",
          "slug": "project-manager"
        },
        {
          "level": 2,
          "title": "快捷键",
          "slug": "快捷键"
        },
        {
          "level": 3,
          "title": "常用快捷键",
          "slug": "常用快捷键"
        },
        {
          "level": 3,
          "title": "自定义快捷键",
          "slug": "自定义快捷键"
        },
        {
          "level": 2,
          "title": "代码提示",
          "slug": "代码提示"
        },
        {
          "level": 3,
          "title": "自定义代码提示与快捷输入",
          "slug": "自定义代码提示与快捷输入"
        }
      ]
    },
    {
      "title": "Vite相关插件",
      "frontmatter": {
        "title": "Vite相关插件",
        "date": "2022-04-10T00:00:00.000Z",
        "tags": [
          "vue",
          "vite"
        ]
      },
      "regularPath": "/tools/Vite.html",
      "relativePath": "tools/Vite.md",
      "key": "v-77f45c45",
      "path": "/tools/Vite.html",
      "headers": [
        {
          "level": 2,
          "title": "unplugin-auto-import",
          "slug": "unplugin-auto-import"
        },
        {
          "level": 3,
          "title": "响应式语法糖",
          "slug": "响应式语法糖"
        },
        {
          "level": 2,
          "title": "unplugin-vue-components",
          "slug": "unplugin-vue-components"
        },
        {
          "level": 2,
          "title": "unplugin-vue-define-options/vite",
          "slug": "unplugin-vue-define-options-vite"
        },
        {
          "level": 2,
          "title": "vite-plugin-mock",
          "slug": "vite-plugin-mock"
        },
        {
          "level": 2,
          "title": "vite-plugin-pages",
          "slug": "vite-plugin-pages"
        },
        {
          "level": 2,
          "title": "vite-plugin-vue-layouts",
          "slug": "vite-plugin-vue-layouts"
        },
        {
          "level": 2,
          "title": "vite-plugin-purge-icons",
          "slug": "vite-plugin-purge-icons"
        },
        {
          "level": 2,
          "title": "vite-plugin-windicss",
          "slug": "vite-plugin-windicss"
        },
        {
          "level": 2,
          "title": "vite-plugin-node",
          "slug": "vite-plugin-node"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Wappalyzer识别网站上的技术",
      "frontmatter": {
        "title": "Wappalyzer识别网站上的技术",
        "date": "2021-07-20T00:00:00.000Z",
        "tags": [
          "chrome",
          "插件"
        ],
        "keywords": [
          "chrome",
          "插件"
        ]
      },
      "regularPath": "/tools/Wappalyzer.html",
      "relativePath": "tools/Wappalyzer.md",
      "key": "v-e040e472",
      "path": "/tools/Wappalyzer.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "开始",
          "slug": "开始"
        }
      ]
    },
    {
      "title": "Windows自定义右键菜单",
      "frontmatter": {
        "title": "Windows自定义右键菜单",
        "date": "2020-09-08T00:00:00.000Z",
        "tags": [
          "工具"
        ],
        "keywords": [
          "工具"
        ]
      },
      "regularPath": "/tools/Windows.html",
      "relativePath": "tools/Windows.md",
      "key": "v-790fa7ae",
      "path": "/tools/Windows.html",
      "headers": [
        {
          "level": 2,
          "title": "开始操作",
          "slug": "开始操作"
        },
        {
          "level": 3,
          "title": "打开注册表",
          "slug": "打开注册表"
        },
        {
          "level": 3,
          "title": "右键打开 Cmd",
          "slug": "右键打开-cmd"
        },
        {
          "level": 3,
          "title": "右键空白区域的菜单",
          "slug": "右键空白区域的菜单"
        },
        {
          "level": 3,
          "title": "右键文件夹菜单",
          "slug": "右键文件夹菜单"
        },
        {
          "level": 3,
          "title": "右键程序菜单",
          "slug": "右键程序菜单"
        },
        {
          "level": 3,
          "title": "右键手动新建",
          "slug": "右键手动新建"
        },
        {
          "level": 2,
          "title": "这里补充一个",
          "slug": "这里补充一个"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Windows Terminal美化",
      "frontmatter": {
        "title": "Windows Terminal美化",
        "date": "2021-05-04T00:00:00.000Z",
        "tags": [
          "Terminal",
          "美化"
        ],
        "keywords": [
          "Terminal",
          "美化"
        ]
      },
      "regularPath": "/tools/WindowsTerminal.html",
      "relativePath": "tools/WindowsTerminal.md",
      "key": "v-06fb3fa9",
      "path": "/tools/WindowsTerminal.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "更改 powershell",
          "slug": "更改-powershell"
        },
        {
          "level": 3,
          "title": "下载模块",
          "slug": "下载模块"
        },
        {
          "level": 3,
          "title": "安装主题",
          "slug": "安装主题"
        },
        {
          "level": 3,
          "title": "修改主题",
          "slug": "修改主题"
        },
        {
          "level": 3,
          "title": "添加 GitBash",
          "slug": "添加-gitbash"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "开发工具推荐",
      "frontmatter": {
        "title": "开发工具推荐"
      },
      "regularPath": "/tools/introduction.html",
      "relativePath": "tools/introduction.md",
      "key": "v-2f5369ce",
      "path": "/tools/introduction.html"
    },
    {
      "title": "Troubleshooting VuePress Issues",
      "frontmatter": {},
      "regularPath": "/troubleshooting.html",
      "relativePath": "troubleshooting.md",
      "key": "v-4f7d2756",
      "path": "/troubleshooting.html",
      "headers": [
        {
          "level": 2,
          "title": "Problem: Site Not Building",
          "slug": "problem-site-not-building"
        },
        {
          "level": 2,
          "title": "Problem: Images Not Displaying",
          "slug": "problem-images-not-displaying"
        },
        {
          "level": 2,
          "title": "Problem: Navigation Not Updating",
          "slug": "problem-navigation-not-updating"
        },
        {
          "level": 2,
          "title": "Problem: Customization Issues",
          "slug": "problem-customization-issues"
        },
        {
          "level": 2,
          "title": "Problem: Deployment Errors",
          "slug": "problem-deployment-errors"
        },
        {
          "level": 2,
          "title": "Problem: SEO Not Optimized",
          "slug": "problem-seo-not-optimized"
        },
        {
          "level": 2,
          "title": "Problem: Slow Performance",
          "slug": "problem-slow-performance"
        },
        {
          "level": 2,
          "title": "Problem: Plugin Conflicts",
          "slug": "problem-plugin-conflicts"
        },
        {
          "level": 2,
          "title": "Problem: Unexpected Behavior",
          "slug": "problem-unexpected-behavior"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": "VuePress快速入门",
        "actionText": "快速开始 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ]
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-14b97908",
      "path": "/zh/"
    },
    {
      "title": "关于本站",
      "frontmatter": {},
      "regularPath": "/zh/about/",
      "relativePath": "zh/about/README.md",
      "key": "v-439dc98a",
      "path": "/zh/about/"
    },
    {
      "title": "关于本站",
      "frontmatter": {
        "id": "about",
        "slug": "/about",
        "title": "关于本站"
      },
      "regularPath": "/zh/about/about.html",
      "relativePath": "zh/about/about.md",
      "key": "v-fed92c70",
      "path": "/zh/about/about.html",
      "headers": [
        {
          "level": 2,
          "title": "本站定位",
          "slug": "本站定位"
        },
        {
          "level": 2,
          "title": "部署方案",
          "slug": "部署方案"
        },
        {
          "level": 2,
          "title": "感谢观看",
          "slug": "感谢观看"
        }
      ]
    },
    {
      "title": "qq",
      "frontmatter": {
        "title": "qq"
      },
      "regularPath": "/zh/about/contact/qq.html",
      "relativePath": "zh/about/contact/qq.md",
      "key": "v-6f9fd7dd",
      "path": "/zh/about/contact/qq.html"
    },
    {
      "title": "微信",
      "frontmatter": {
        "title": "微信"
      },
      "regularPath": "/zh/about/contact/wechat.html",
      "relativePath": "zh/about/contact/wechat.md",
      "key": "v-19645b9d",
      "path": "/zh/about/contact/wechat.html"
    },
    {
      "title": "博客",
      "frontmatter": {
        "blog_index": true
      },
      "regularPath": "/zh/blog/",
      "relativePath": "zh/blog/README.md",
      "key": "v-8b84b3c6",
      "path": "/zh/blog/"
    },
    {
      "title": "标题1",
      "frontmatter": {
        "title": "标题1",
        "date": "2023-09-28T00:00:00.000Z",
        "description": "这是一个描述"
      },
      "regularPath": "/zh/blog/test1.html",
      "relativePath": "zh/blog/test1.md",
      "key": "v-d992ded4",
      "path": "/zh/blog/test1.html"
    },
    {
      "title": "我激动人心的VuePress博客之旅",
      "frontmatter": {
        "title": "我激动人心的VuePress博客之旅",
        "date": "2023-09-28T00:00:00.000Z",
        "description": "探索VuePress，一个多功能的静态网站生成器，并分享我的经验。"
      },
      "regularPath": "/zh/blog/first-post.html",
      "relativePath": "zh/blog/first-post.md",
      "key": "v-02881e60",
      "path": "/zh/blog/first-post.html"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-4db4fb9b",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "静态网站托管",
          "slug": "静态网站托管"
        }
      ]
    },
    {
      "title": "Kinsta静态网站托管的工作原理",
      "frontmatter": {},
      "regularPath": "/zh/guide/using-kinsta-stsh.html",
      "relativePath": "zh/guide/using-kinsta-stsh.md",
      "key": "v-491ccd20",
      "path": "/zh/guide/using-kinsta-stsh.html"
    },
    {
      "title": "Everything快速搜索本地文件",
      "frontmatter": {
        "title": "Everything快速搜索本地文件",
        "date": "2020-09-08T00:00:00.000Z",
        "tags": [
          "工具"
        ],
        "keywords": [
          "工具"
        ]
      },
      "regularPath": "/zh/tools/Everything.html",
      "relativePath": "zh/tools/Everything.md",
      "key": "v-65f4cd30",
      "path": "/zh/tools/Everything.html",
      "headers": [
        {
          "level": 2,
          "title": "软件说明",
          "slug": "软件说明"
        },
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 3,
          "title": "设置打开快捷键",
          "slug": "设置打开快捷键"
        },
        {
          "level": 2,
          "title": "搜索文件",
          "slug": "搜索文件"
        },
        {
          "level": 3,
          "title": "右键搜索 Everything",
          "slug": "右键搜索-everything"
        },
        {
          "level": 2,
          "title": "一些注意的坑",
          "slug": "一些注意的坑"
        },
        {
          "level": 3,
          "title": "全字匹配",
          "slug": "全字匹配"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "IDEA基本配置",
      "frontmatter": {
        "title": "IDEA基本配置",
        "date": "2022-01-06T00:00:00.000Z",
        "tags": [
          "Jetbrains",
          "idea",
          "java",
          "工具"
        ],
        "keywords": [
          "Jetbrains",
          "idea",
          "java",
          "工具"
        ]
      },
      "regularPath": "/zh/tools/IDEA.html",
      "relativePath": "zh/tools/IDEA.md",
      "key": "v-4ae869b0",
      "path": "/zh/tools/IDEA.html",
      "headers": [
        {
          "level": 2,
          "title": "插件",
          "slug": "插件"
        },
        {
          "level": 3,
          "title": "主题图标",
          "slug": "主题图标"
        },
        {
          "level": 2,
          "title": "快捷键",
          "slug": "快捷键"
        },
        {
          "level": 3,
          "title": "Ctrl",
          "slug": "ctrl"
        },
        {
          "level": 3,
          "title": "Alt",
          "slug": "alt"
        },
        {
          "level": 3,
          "title": "Ctrl + Alt",
          "slug": "ctrl-alt"
        },
        {
          "level": 3,
          "title": "Ctrl + Shift",
          "slug": "ctrl-shift"
        },
        {
          "level": 3,
          "title": "Alt + Shift",
          "slug": "alt-shift"
        },
        {
          "level": 3,
          "title": "调试",
          "slug": "调试"
        },
        {
          "level": 3,
          "title": "自定义",
          "slug": "自定义"
        },
        {
          "level": 2,
          "title": "其他操作",
          "slug": "其他操作"
        },
        {
          "level": 3,
          "title": "快速生成代码",
          "slug": "快速生成代码"
        },
        {
          "level": 3,
          "title": "修改 Maven 依赖仓库位置",
          "slug": "修改-maven-依赖仓库位置"
        },
        {
          "level": 2,
          "title": "配置导入与导出",
          "slug": "配置导入与导出"
        }
      ]
    },
    {
      "title": "Jetbrains系列产品激活方法",
      "frontmatter": {
        "title": "Jetbrains系列产品激活方法",
        "date": "2020-09-03T00:00:00.000Z",
        "tags": [
          "Jetbrains",
          "工具"
        ],
        "keywords": [
          "Jetbrains",
          "工具"
        ]
      },
      "regularPath": "/zh/tools/Jetbrains.html",
      "relativePath": "zh/tools/Jetbrains.md",
      "key": "v-ece49d4c",
      "path": "/zh/tools/Jetbrains.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "开始激活",
          "slug": "开始激活"
        },
        {
          "level": 3,
          "title": "下载激活工具",
          "slug": "下载激活工具"
        },
        {
          "level": 3,
          "title": "运行要激活的软件",
          "slug": "运行要激活的软件"
        },
        {
          "level": 3,
          "title": "补充几点",
          "slug": "补充几点"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "工具推荐",
      "frontmatter": {},
      "regularPath": "/zh/tools/",
      "relativePath": "zh/tools/README.md",
      "key": "v-589c9c0a",
      "path": "/zh/tools/"
    },
    {
      "title": "VScode相关配置",
      "frontmatter": {
        "title": "VScode相关配置",
        "date": "2021-08-03T00:00:00.000Z",
        "tags": [
          "vscode",
          "开发工具",
          "配置"
        ],
        "keywords": [
          "vscode",
          "开发工具",
          "配置"
        ]
      },
      "regularPath": "/zh/tools/VScode.html",
      "relativePath": "zh/tools/VScode.md",
      "key": "v-f21846e0",
      "path": "/zh/tools/VScode.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "插件推荐",
          "slug": "插件推荐"
        },
        {
          "level": 3,
          "title": "GitHub Copilot",
          "slug": "github-copilot"
        },
        {
          "level": 3,
          "title": "Bracket Pair Colorizer 2",
          "slug": "bracket-pair-colorizer-2"
        },
        {
          "level": 3,
          "title": "indent-rainbow",
          "slug": "indent-rainbow"
        },
        {
          "level": 3,
          "title": "Prettier",
          "slug": "prettier"
        },
        {
          "level": 3,
          "title": "ESLint",
          "slug": "eslint"
        },
        {
          "level": 3,
          "title": "Turbo Console Log",
          "slug": "turbo-console-log"
        },
        {
          "level": 3,
          "title": "Live Server",
          "slug": "live-server"
        },
        {
          "level": 3,
          "title": "Live Share",
          "slug": "live-share"
        },
        {
          "level": 3,
          "title": "REST Client",
          "slug": "rest-client"
        },
        {
          "level": 3,
          "title": "Thunder Client",
          "slug": "thunder-client"
        },
        {
          "level": 3,
          "title": "CSS Peek",
          "slug": "css-peek"
        },
        {
          "level": 3,
          "title": "Project Manager",
          "slug": "project-manager"
        },
        {
          "level": 2,
          "title": "快捷键",
          "slug": "快捷键"
        },
        {
          "level": 3,
          "title": "常用快捷键",
          "slug": "常用快捷键"
        },
        {
          "level": 3,
          "title": "自定义快捷键",
          "slug": "自定义快捷键"
        },
        {
          "level": 2,
          "title": "代码提示",
          "slug": "代码提示"
        },
        {
          "level": 3,
          "title": "自定义代码提示与快捷输入",
          "slug": "自定义代码提示与快捷输入"
        }
      ]
    },
    {
      "title": "Vite相关插件",
      "frontmatter": {
        "title": "Vite相关插件",
        "date": "2022-04-10T00:00:00.000Z",
        "tags": [
          "vue",
          "vite"
        ]
      },
      "regularPath": "/zh/tools/Vite.html",
      "relativePath": "zh/tools/Vite.md",
      "key": "v-a02ffbe0",
      "path": "/zh/tools/Vite.html",
      "headers": [
        {
          "level": 2,
          "title": "unplugin-auto-import",
          "slug": "unplugin-auto-import"
        },
        {
          "level": 3,
          "title": "响应式语法糖",
          "slug": "响应式语法糖"
        },
        {
          "level": 2,
          "title": "unplugin-vue-components",
          "slug": "unplugin-vue-components"
        },
        {
          "level": 2,
          "title": "unplugin-vue-define-options/vite",
          "slug": "unplugin-vue-define-options-vite"
        },
        {
          "level": 2,
          "title": "vite-plugin-mock",
          "slug": "vite-plugin-mock"
        },
        {
          "level": 2,
          "title": "vite-plugin-pages",
          "slug": "vite-plugin-pages"
        },
        {
          "level": 2,
          "title": "vite-plugin-vue-layouts",
          "slug": "vite-plugin-vue-layouts"
        },
        {
          "level": 2,
          "title": "vite-plugin-purge-icons",
          "slug": "vite-plugin-purge-icons"
        },
        {
          "level": 2,
          "title": "vite-plugin-windicss",
          "slug": "vite-plugin-windicss"
        },
        {
          "level": 2,
          "title": "vite-plugin-node",
          "slug": "vite-plugin-node"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Wappalyzer识别网站上的技术",
      "frontmatter": {
        "title": "Wappalyzer识别网站上的技术",
        "date": "2021-07-20T00:00:00.000Z",
        "tags": [
          "chrome",
          "插件"
        ],
        "keywords": [
          "chrome",
          "插件"
        ]
      },
      "regularPath": "/zh/tools/Wappalyzer.html",
      "relativePath": "zh/tools/Wappalyzer.md",
      "key": "v-a184b1a0",
      "path": "/zh/tools/Wappalyzer.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "开始",
          "slug": "开始"
        }
      ]
    },
    {
      "title": "Windows自定义右键菜单",
      "frontmatter": {
        "title": "Windows自定义右键菜单",
        "date": "2020-09-08T00:00:00.000Z",
        "tags": [
          "工具"
        ],
        "keywords": [
          "工具"
        ]
      },
      "regularPath": "/zh/tools/Windows.html",
      "relativePath": "zh/tools/Windows.md",
      "key": "v-3093d100",
      "path": "/zh/tools/Windows.html",
      "headers": [
        {
          "level": 2,
          "title": "开始操作",
          "slug": "开始操作"
        },
        {
          "level": 3,
          "title": "打开注册表",
          "slug": "打开注册表"
        },
        {
          "level": 3,
          "title": "右键打开 Cmd",
          "slug": "右键打开-cmd"
        },
        {
          "level": 3,
          "title": "右键空白区域的菜单",
          "slug": "右键空白区域的菜单"
        },
        {
          "level": 3,
          "title": "右键文件夹菜单",
          "slug": "右键文件夹菜单"
        },
        {
          "level": 3,
          "title": "右键程序菜单",
          "slug": "右键程序菜单"
        },
        {
          "level": 3,
          "title": "右键手动新建",
          "slug": "右键手动新建"
        },
        {
          "level": 2,
          "title": "这里补充一个",
          "slug": "这里补充一个"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Windows Terminal美化",
      "frontmatter": {
        "title": "Windows Terminal美化",
        "date": "2021-05-04T00:00:00.000Z",
        "tags": [
          "Terminal",
          "美化"
        ],
        "keywords": [
          "Terminal",
          "美化"
        ]
      },
      "regularPath": "/zh/tools/WindowsTerminal.html",
      "relativePath": "zh/tools/WindowsTerminal.md",
      "key": "v-62c3e948",
      "path": "/zh/tools/WindowsTerminal.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "更改 powershell",
          "slug": "更改-powershell"
        },
        {
          "level": 3,
          "title": "下载模块",
          "slug": "下载模块"
        },
        {
          "level": 3,
          "title": "安装主题",
          "slug": "安装主题"
        },
        {
          "level": 3,
          "title": "修改主题",
          "slug": "修改主题"
        },
        {
          "level": 3,
          "title": "添加 GitBash",
          "slug": "添加-gitbash"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "开发工具推荐",
      "frontmatter": {
        "title": "开发工具推荐"
      },
      "regularPath": "/zh/tools/introduction.html",
      "relativePath": "zh/tools/introduction.md",
      "key": "v-514bcf60",
      "path": "/zh/tools/introduction.html"
    }
  ],
  "themeConfig": {
    "lastUpdated": "Last Updated",
    "sidebarDepth": 1,
    "displayAllHeaders": false,
    "activeHeaderLinks": true,
    "search": true,
    "locales": {
      "/": {
        "selectText": "Languages",
        "label": "English",
        "ariaLabel": "Languages",
        "serviceWorker": {
          "updatePopup": {
            "message": "New content is available.",
            "buttonText": "Refresh"
          }
        },
        "algolia": {},
        "nav": [
          {
            "text": "Guide",
            "link": "/guide/"
          },
          {
            "text": "Blog",
            "link": "/blog/"
          },
          {
            "text": "About",
            "link": "/about/"
          },
          {
            "text": "Tools",
            "link": "/tools/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "Guide",
              "collapsable": false,
              "children": [
                "",
                "using-kinsta-stsh"
              ]
            }
          ],
          "/about/": [
            {
              "title": "About this site",
              "collapsable": false,
              "children": [
                "about"
              ]
            },
            {
              "title": "Contact information",
              "children": [
                "contact/qq",
                "contact/wechat"
              ]
            }
          ],
          "/tools/": [
            {
              "title": "Tools",
              "children": [
                "Everything",
                "IDEA"
              ]
            }
          ]
        }
      },
      "/zh/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "serviceWorker": {
          "updatePopup": {
            "message": "发现新内容可用.",
            "buttonText": "刷新"
          }
        },
        "algolia": {},
        "nav": [
          {
            "text": "指导",
            "link": "/zh/guide/"
          },
          {
            "text": "博客",
            "link": "/zh/blog/"
          },
          {
            "text": "关于本站",
            "link": "/zh/about/"
          },
          {
            "text": "工具推荐",
            "link": "/zh/tools/"
          }
        ],
        "sidebar": {
          "/zh/guide/": [
            {
              "title": "指导",
              "collapsable": false,
              "children": [
                "",
                "using-kinsta-stsh"
              ]
            }
          ],
          "/zh/about/": [
            {
              "title": "关于本站",
              "collapsable": false,
              "children": [
                "about"
              ]
            },
            {
              "title": "联系方式",
              "children": [
                "contact/qq",
                "contact/wechat"
              ]
            }
          ],
          "/zh/tools/": [
            {
              "title": "工具推荐",
              "children": [
                "Everything",
                "IDEA"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "XXX System",
      "description": "Vue-powered Static Site Generator",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "XXX系统",
      "description": "Vue 驱动的静态网站生成器",
      "path": "/zh/"
    }
  }
}